apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t041q0p5r-java-quarkus
  janus-idp.io/tekton: t041q0p5r-java-quarkus
  backstage.io/kubernetes-id: t041q0p5r-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t041q0p5r-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
